apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - name: time-check
    image: busybox
    command: ["while true; do date; sleep $(TIME_FREQ);done"]
    volumeMounts:
    - name: log-storage
      mountPath: /opt/time
    env:
      - name: TIME_FREQ
        valueFrom:
          configMapKeyRef:
            name: time-config
            key: TIME_FREQ
  volumes:
    - name: log-storage
      emptyDir: {}


apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ: '10'