apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
spec:
  completions: 10
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay
        command: ["echo", "cowsay I am going to ace CKAD!"]
      restartPolicy: Never
  backoffLimit: 6