apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31004
      name: http
  selector:
    app: wordpress