apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
  labels:
    app: log
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/opt/volume/nginx"