apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-sec-kff3345
  name: app-sec-kff3345
spec:
  containers:
  - image: ubuntu
    name: app-sec-kff3345
    resources: {}
    securityContext:
     capabilities:
      add: ["SYS_TIME"]
