apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: log-storage
      mountPath: /var/www/nginx
  volumes:
    - name: log-storage
      # use persistent volume claim
      persistentVolumeClaim:
        claimName: log-claim